version: '3.8'

services:
  app:
    build: .
    container_name: CommerceMail-app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - mongo
      - redis
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
      SPRING_DATA_REDIS_HOST: redis
    networks:
      - backend

  postgres:
    container_name: CommerceMail-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: CommerceMail
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    container_name: CommerceMail-mongo
    image: mongo:4
    ports:
      - '27017:27017'
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: CommerceMail-redis
    image: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - backend

volumes:
  postgres-data:
  mongo-data:

networks:
  backend: