version: '3.8'

services:
  app:
    build: .
    container_name: CommerceMail-app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/CommerceMail
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/CommerceMail
    networks:
      - backend

  postgres:
    container_name: CommerceMail-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: CommerceMail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    container_name: CommerceMail-mongo
    image: mongo:4
    ports:
      - '27017:27017'
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: CommerceMail-redis
    image: redis
    restart: no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

volumes:
  postgres-data:
  mongo-data:

networks:
  backend:
