CREATE TABLE carts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    total_price NUMERIC(10,2) DEFAULT 0.00,
    status VARCHAR(50),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE cart_products (
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER DEFAULT 1,
    PRIMARY KEY (cart_id, product_id),
    CONSTRAINT fk_cart_products_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_products_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);
