ALTER TABLE users DROP COLUMN id;
ALTER TABLE users ADD COLUMN id BIGSERIAL PRIMARY KEY;

ALTER TABLE administrator DROP COLUMN id;
ALTER TABLE administrator ADD COLUMN id BIGSERIAL PRIMARY KEY;

ALTER TABLE product DROP COLUMN id;
ALTER TABLE product ADD COLUMN id BIGSERIAL PRIMARY KEY;